server {
    listen 80;
    server_name 213.136.86.156;   # plus tard : ton-domaine.com

    root /usr/share/nginx/html;
    index index.html index.htm;

    # Angular SPA routing
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy vers Spring Boot (contexte /Ecole)
    location /Ecole/ {
        proxy_pass http://backend:8080/Ecole/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Cache des assets statiques
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2?)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}